### ISSUE TITLE
Focus mode

### ISSUE THREAD

**Issue by lukepighetti** [blaugold/melos-code#29]
I noticed some monorepo tools allow for focus mode. 

Use case: I want to work on package B (which depends on package A), but I don't want to see, or have analyzer consider, packages C, D, E ... n

`melos focus <package_name>`

Would resolve it's dependencies and hide everything else.

This may inspire a change where an app needs to be defined in `melos.yaml` so that it too can be hidden from analyzer, otherwise it will just show a bunch of IDE errors whenever focus mode is enabled

**Comment by blaugold** [comment]
Issue #26 sounds a lot like what you want. Does it cover your use case?

**Comment by lukepighetti** [comment]
It covers it for Visual Studio Code users. Luckily I am one. Maybe this can track the concept generally. I believe some monorepo tools out there use git features to hide parts of the codebase temporarily. Unfortunately I haven't spent much time on this to be able to give any concrete examples. I believe @chigibb1 has some more context on this

**Comment by blaugold** [comment]
I haven't though about that possibility, but it would be great to have this as a feature that works for all IDEs and from the command line!

Since this would have to be implemented in Melos directly, and this is the repo for the Melos VS Code extension, please file this features request in the [Melos repo](https://github.com/invertase/melos).

**Comment by lukepighetti** [comment]
My mistake, I must have submitted this to the wrong repo.
